### ISSUE TITLE
why? How? train error 0%| | 0/100000 [00:00<?, ?it/s]

### ISSUE THREAD

**Issue by isyanan1024** [princeton-vl/CornerNet-Lite#104]
Traceback (most recent call last):
  File "/root/anaconda3/envs/CornerNet_Lite/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/root/anaconda3/envs/CornerNet_Lite/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/root/anaconda3/envs/CornerNet_Lite/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 295, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_5807_1602858868>
setting learning rate to: 0.00025
training start...
  0%| | 0/100000 [00:00<?, ?it/s]

**Comment by isyanan1024** [comment]
please，help me

**Comment by apatsekin** [comment]
if you are using docker, try to run it with ` --ipc=host` flag

**Comment by isyanan1024** [comment]
> if you are using docker, try to run it with ` --ipc=host` flag

it works.Thank you.So happy

**Comment by Xuan-ing** [comment]
what if not? I encounter the same problem with him. Thanks.

**Comment by ZeKunZhang1998** [comment]
> 如果您使用的是docker，请尝试使用` --ipc=host`flag 运行它

hello,where can i add this command？

**Comment by Fuhan1994** [comment]
i met the same problem , but i did not use docker, so how can i solve the problem?
