### ISSUE TITLE
There is a problem during training

### ISSUE THREAD

**Issue by float4189** [princeton-vl/CornerNet-Lite#113]
Hello everyone, how can this problem solve you?

shuffling indices...
start prefetching data...
setting learning rate to: 0.00025
training start...
shuffling indices...
  0%|                                                | 0/500000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 249, in <module>
    main(None, ngpus_per_node, args)
  File "train.py", line 233, in main
    train(training_dbs, validation_db, system_config, model, args)
  File "train.py", line 165, in train
    training_loss = nnet.train(**training)
  File "/home/hyb/MyFile/MyCode/CornerNet-Lite/core/nnet/py_factory.py", line 93, in train
    loss = self.network(xs, ys)
  File "/home/hyb/anaconda3/envs/hyb_CornerNet_Lite/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyb/MyFile/MyCode/CornerNet-Lite/core/models/py_utils/data_parallel.py", line 66, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids, self.chunk_sizes)
  File "/home/hyb/MyFile/MyCode/CornerNet-Lite/core/models/py_utils/data_parallel.py", line 77, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim, chunk_sizes=self.chunk_sizes)
  File "/home/hyb/MyFile/MyCode/CornerNet-Lite/core/models/py_utils/scatter_gather.py", line 30, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim, chunk_sizes) if inputs else []
  File "/home/hyb/MyFile/MyCode/CornerNet-Lite/core/models/py_utils/scatter_gather.py", line 25, in scatter
    return scatter_map(inputs)
  File "/home/hyb/MyFile/MyCode/CornerNet-Lite/core/models/py_utils/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/hyb/MyFile/MyCode/CornerNet-Lite/core/models/py_utils/scatter_gather.py", line 20, in scatter_map
    return list(map(list, zip(*map(scatter_map, obj))))
  File "/home/hyb/MyFile/MyCode/CornerNet-Lite/core/models/py_utils/scatter_gather.py", line 15, in scatter_map
    return Scatter.apply(target_gpus, chunk_sizes, dim, obj)
  File "/home/hyb/anaconda3/envs/hyb_CornerNet_Lite/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/hyb/anaconda3/envs/hyb_CornerNet_Lite/lib/python3.7/site-packages/torch/cuda/comm.py", line 147, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
**RuntimeError: given chunk sizes don't sum up to the tensor's size (sum(chunk_sizes) == 48, but expected 2) (scatter at /tmp/pip-req-build-58y_cjjl/torch/csrc/cuda/comm.cpp:176)**
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7f78398761cd in /home/hyb/anaconda3/envs/hyb_CornerNet_Lite/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: torch::cuda::scatter(at::Tensor const&, c10::ArrayRef<long>, c10::optional<std::vector<long, std::allocator<long> > > const&, long, c10::optional<std::vector<c10::optional<c10::cuda::CUDAStream>, std::allocator<c10::optional<c10::cuda::CUDAStream> > > > const&) + 0x10d3 (0x7f783d6f7393 in /home/hyb/anaconda3/envs/hyb_CornerNet_Lite/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x62268e (0x7f785c36668e in /home/hyb/anaconda3/envs/hyb_CornerNet_Lite/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x1c7126 (0x7f785bf0b126 in /home/hyb/anaconda3/envs/hyb_CornerNet_Lite/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #11: THPFunction_apply(_object*, _object*) + 0xa56 (0x7f785c1395f6 in /home/hyb/anaconda3/envs/hyb_CornerNet_Lite/lib/python3.7/site-packages/torch/lib/libtorch_python.so)

**Comment by samsara1995** [comment]
how do you solve the problem?

**Comment by ChengxuLiu** [comment]
You can see 'given chunk sizes don't sum up to the tensor's size (sum(chunk_sizes) == 48, but expected 2) ' . you must train this on one GPU.  It means that your chunk_sizes is fault, and it is the distribute condition the data in different gpu. You can see the config file 'CenterNet.json'  ,you only change the "batch_size" to 2, and the "chunk_sizes" you have not change, you should change "chunk_sizes" to [2] to solve this problem.
