### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by fengzifrank** [princeton-vl/CornerNet-Lite#12]
An error occurred during training Can you show your dataset tree directory? Thank you (the following is my structure according to the document)
---CornerNet-Lite
     ---data
          ---coco   
               --- images
                     ---trainval2014
                          ---train2014.zip
                     ---minival2014
                          ---val2014.zip
                     ---testdev2017
                          ---test2017.zip

run   python train.py CornerNet_Saccade --workers=1

File "train.py", line 55, in prefetch_data
    data, ind = sample_data(system_config, db, ind, data_aug=data_aug)
  File "/test/CornerNet-Lite/core/sample/__init__.py", line 5, in data_sampling_func
    return globals()[sys_configs.sampling_function](sys_configs, db, k_ind, data_aug, debug)
  File "/test/CornerNet-Lite/core/sample/cornernet_saccade.py", line 169, in cornernet_saccade
    border     = [0, image.shape[0], 0, image.shape[1]]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/envs/CornerNet_Lite/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/CornerNet_Lite/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 59, in prefetch_data
    raise e
  File "train.py", line 55, in prefetch_data
    data, ind = sample_data(system_config, db, ind, data_aug=data_aug)
  File "/test/CornerNet-Lite/core/sample/__init__.py", line 5, in data_sampling_func
    return globals()[sys_configs.sampling_function](sys_configs, db, k_ind, data_aug, debug)
  File "/test/CornerNet-Lite/core/sample/cornernet_saccade.py", line 169, in cornernet_saccade
    border     = [0, image.shape[0], 0, image.shape[1]]
AttributeError: 'NoneType' object has no attribute 'shape'
setting learning rate to: 0.00025
training start...
start prefetching data...
shuffling indices...
Traceback (most recent call last):
  File "train.py", line 55, in prefetch_data
    data, ind = sample_data(system_config, db, ind, data_aug=data_aug)
  File "/test/CornerNet-Lite/core/sample/__init__.py", line 5, in data_sampling_func
    return globals()[sys_configs.sampling_function](sys_configs, db, k_ind, data_aug, debug)
  File "/test/CornerNet-Lite/core/sample/cornernet_saccade.py", line 169, in cornernet_saccade
    border     = [0, image.shape[0], 0, image.shape[1]]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/CornerNet_Lite/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/CornerNet_Lite/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 59, in prefetch_data
    raise e
  File "train.py", line 55, in prefetch_data
    data, ind = sample_data(system_config, db, ind, data_aug=data_aug)
  File "/test/CornerNet-Lite/core/sample/__init__.py", line 5, in data_sampling_func
    return globals()[sys_configs.sampling_function](sys_configs, db, k_ind, data_aug, debug)
  File "/test/CornerNet-Lite/core/sample/cornernet_saccade.py", line 169, in cornernet_saccade
    border     = [0, image.shape[0], 0, image.shape[1]]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by ray2004a** [comment]
I met the same problem, does anyone find the solution to this problem?

**Comment by SeeeeShiwei** [comment]
I met the same problem, does anyone find the solution to this problem?

**Comment by ghost** [comment]
same issue, have someone solved this???

**Comment by leekunpeng** [comment]
put images in minival2014 into trainval2014
