### ISSUE TITLE
error in evaluate the model

### ISSUE THREAD

**Issue by qrt159** [princeton-vl/CornerNet-Lite#133]
when i run evaluate.py, I get some trouble like this: 

Traceback (most recent call last):
  File "evaluate.py", line 104, in <module>
    main(args)
  File "evaluate.py", line 100, in main
    test(testing_db, system_config, model, args)
  File "evaluate.py", line 60, in test
    test_func(system_config, db, nnet, result_dir, debug=debug)
  File "/qinruntian/CornerNet-Lite/core/test/__init__.py", line 11, in test_func
    return globals()[sys_config.sampling_function](db, nnet, result_dir, debug=debug)
  File "/qinruntian/CornerNet-Lite/core/test/cornernet_saccade.py", line 284, in cornernet_saccade
    json.dump(detections, f)
  File "/root/anaconda3/envs/CornerNet_Lite/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/root/anaconda3/envs/CornerNet_Lite/lib/python3.7/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/root/anaconda3/envs/CornerNet_Lite/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/root/anaconda3/envs/CornerNet_Lite/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/root/anaconda3/envs/CornerNet_Lite/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/root/anaconda3/envs/CornerNet_Lite/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable

what can i do to solve this problem?

**Comment by heilaw** [comment]
Were you evaluating the model on your own dataset?
