### ISSUE TITLE
ImportError undefined symbol: _ZNSt19basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

### ISSUE THREAD

**Issue by zielona1** [princeton-vl/CornerNet-Lite#155]
run the Demo Script
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from core.detectors import CornerNet_Saccade
  File "/home/zielona/CornerNet-Lite/core/detectors.py", line 1, in <module>
    from .base import Base, load_cfg, load_nnet
  File "/home/zielona/CornerNet-Lite/core/base.py", line 3, in <module>
    from .nnet.py_factory import NetworkFactory
  File "/home/zielona/CornerNet-Lite/core/nnet/py_factory.py", line 7, in <module>
    from ..models.py_utils.data_parallel import DataParallel
  File "/home/zielona/CornerNet-Lite/core/models/py_utils/__init__.py", line 1, in <module>
    from ._cpools import TopPool, BottomPool, LeftPool, RightPool
  File "/home/zielona/CornerNet-Lite/core/models/py_utils/_cpools/__init__.py", line 6, in <module>
    import top_pool, bottom_pool, left_pool, right_pool
ImportError: /home/zielona/.local/lib/python3.7/site-packages/cpools-0.0.0-py3.7-linux-x86_64.egg/top_pool.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt19basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

**Comment by veredba** [comment]
Hi, I use cuda 11, and I've created the conda env differently:
I removed from the conda_packagelist.txt the following: cuda, pytorch and torchvision
run:
conda create --name CornerNet_Lite --file conda_packagelist.txt --channel pytorch
conda activate CornerNet_Lite
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

I recompiled the "_cpool" and it solved the issue for me.
