### ISSUE TITLE
When I train the model on my own dataset, I met IndexError in cornernet_saccade.py

### ISSUE THREAD

**Issue by imzhangyd** [princeton-vl/CornerNet-Lite#156]
Process Process-5:
Traceback (most recent call last):
  File "/ldap_shared/home/s_zyd/.pyenv/versions/anaconda3-2019.07/envs/CornerNet_Lite/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ldap_shared/home/s_zyd/.pyenv/versions/anaconda3-2019.07/envs/CornerNet_Lite/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 66, in prefetch_data
    raise e
  File "train.py", line 62, in prefetch_data
    data, ind = sample_data(system_config, db, ind, data_aug=data_aug)
  File "/ldap_shared/home/s_zyd/CornerNet-Lite-master/core/sample/__init__.py", line 5, in data_sampling_func
    return globals()[sys_configs.sampling_function](sys_configs, db, k_ind, data_aug, debug)
  File "/ldap_shared/home/s_zyd/CornerNet-Lite-master/core/sample/cornernet_saccade.py", line 202, in cornernet_saccade
    create_attention_mask([att[b_ind, 0] for att in attentions], att_ratios, att_ranges, detections) 
  File "/ldap_shared/home/s_zyd/CornerNet-Lite-master/core/sample/cornernet_saccade.py", line 117, in create_attention_mask
    att[y, x] = 1
IndexError: index 50 is out of bounds for axis 0 with size 32

Note:
My images size is 512*512.
Can you help me?

**Comment by imzhangyd** [comment]
The reason is that the input size was changed as 512 512.
