### ISSUE TITLE
top_pool.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by lijunling** [princeton-vl/CornerNet-Lite#52]
master/core/models/py_utils/_cpools/__init__.py", line 6, in <module>
    import top_pool, bottom_pool, left_pool, right_pool
xxxx/lib/python3.7/site-packages/cpools-0.0.0-py3.7-linux-x86_64.egg/top_pool.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
my gcc is 6.1.0

**Comment by lg920810** [comment]
Have you compiled sucessfully?

**Comment by lijunling** [comment]
yes,when I run demo.py ,it throws the error.

**Comment by dmxj** [comment]
you can try re-pull the code and build it again

**Comment by arcral** [comment]
I built the latest code, and also met question like this.
ImportError: /root/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/top_pool.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

centos7
python 3.6.5
cuda 10.0
PyTorch 1.0.0
gcc 5.3.1

**Comment by wcg5262** [comment]
I have same problem when run demo.py.
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from core.detectors import CornerNet_Saccade
  File "/root/wcg/CornerNet-Lite-master/core/detectors.py", line 1, in <module>
    from .base import Base, load_cfg, load_nnet
  File "/root/wcg/CornerNet-Lite-master/core/base.py", line 3, in <module>
    from .nnet.py_factory import NetworkFactory
  File "/root/wcg/CornerNet-Lite-master/core/nnet/py_factory.py", line 7, in <module>
    from ..models.py_utils.data_parallel import DataParallel
  File "/root/wcg/CornerNet-Lite-master/core/models/py_utils/__init__.py", line 1, in <module>
    from ._cpools import TopPool, BottomPool, LeftPool, RightPool
  File "/root/wcg/CornerNet-Lite-master/core/models/py_utils/_cpools/__init__.py", line 6, in <module>
    import top_pool, bottom_pool, left_pool, right_pool
ImportError: /root/.local/lib/python3.7/site-packages/cpools-0.0.0-py3.7-linux-x86_64.egg/top_pool.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

I change the pytorch to 0.4.1 because my cuda is 9.0.

**Comment by SeeeeShiwei** [comment]
How to solve it? Thanks

**Comment by andyhahaha** [comment]
I have the same error.
gcc 5.4.0

**Comment by feiyuhuahuo** [comment]
If comes with this error:undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs, follow 'Getting started' to create a new environment. Try not to run in your old environment, because it's easy to meet environment incompatible problem. I ran the demo firstly in my own environment and it appears error. Then I create a new environment  and do as the 'Getting started' told, it works succesfully.

**Comment by njustymk** [comment]
怎么解决，我以前是重新编译了一下，但是现在好像重新编译也不行了

**Comment by LewX** [comment]
How to solve it?

**Comment by caikw0602** [comment]
Yes, the same problem.

**Comment by njustymk** [comment]
the same problem. How to solve it?

**Comment by syedibnmohsin** [comment]
I have the same problem, I am running it on VirtualBox. Is it because the VM doesn't have access to the host GPU?

**Comment by lijunling** [comment]
您好，来信已收到！
