### ISSUE TITLE
WIN10下已经解决了安装和训练，还有问题的，可以加Q群264191384 注明（CornerNet-Lite）共同研究，谢谢

### ISSUE THREAD

**Issue by QQ2737499951** [princeton-vl/CornerNet-Lite#70]
WIN10下已经解决了安装和训练，还有问题的，可以加Q群264191384 注明（CornerNet-Lite）共同研究，谢谢

**Comment by Innan666** [comment]
请问我这个问题是怎么回事cuda是10啊

total parameters: 116969339
loading from c:\Users\IFL\Desktop\Liu\Detector\CornerNet-Lite-master\core..\cache\nnet\CornerNet_Saccade\CornerNet_Saccade_500000.pkl
Traceback (most recent call last):
File "c:\Users\IFL.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 43, in 
main(ptvsdArgs)
File "c:\Users\IFL.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd_main_.py", line 434, in main
run()
File "c:\Users\IFL.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd_main_.py", line 312, in run_file
runpy.run_path(target, run_name='main')
File "C:\Users\IFL\Anaconda3\envs\CornerNet_Lite\lib\runpy.py", line 263, in run_path
pkg_name=pkg_name, script_name=fname)
File "C:\Users\IFL\Anaconda3\envs\CornerNet_Lite\lib\runpy.py", line 96, in _run_module_code
mod_name, mod_spec, pkg_name, script_name)
File "C:\Users\IFL\Anaconda3\envs\CornerNet_Lite\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "c:\Users\IFL\Desktop\Liu\Detector\CornerNet-Lite-master\demo.py", line 7, in 
detector = CornerNet_Saccade()
File "c:\Users\IFL\Desktop\Liu\Detector\CornerNet-Lite-master\core\detectors.py", line 49, in init
super(CornerNet_Saccade, self).init(coco, cornernet, cornernet_saccade_inference, model=model_path)
File "c:\Users\IFL\Desktop\Liu\Detector\CornerNet-Lite-master\core\base.py", line 14, in init
self._nnet.load_pretrained_params(model)
File "c:\Users\IFL\Desktop\Liu\Detector\CornerNet-Lite-master\core\nnet\py_factory.py", line 122, in load_pretrained_params
params = torch.load(f)
File "C:\Users\IFL\Anaconda3\envs\CornerNet_Lite\lib\site-packages\torch\serialization.py", line 368, in load
return _load(f, map_location, pickle_module)
File "C:\Users\IFL\Anaconda3\envs\CornerNet_Lite\lib\site-packages\torch\serialization.py", line 542, in _load
result = unpickler.load()
File "C:\Users\IFL\Anaconda3\envs\CornerNet_Lite\lib\site-packages\torch\serialization.py", line 505, in persistent_load
data_type(size), location)
File "C:\Users\IFL\Anaconda3\envs\CornerNet_Lite\lib\site-packages\torch\serialization.py", line 114, in default_restore_location
result = fn(storage, location)
File "C:\Users\IFL\Anaconda3\envs\CornerNet_Lite\lib\site-packages\torch\serialization.py", line 95, in _cuda_deserialize
device = validate_cuda_device(location)
File "C:\Users\IFL\Anaconda3\envs\CornerNet_Lite\lib\site-packages\torch\serialization.py", line 79, in validate_cuda_device
raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.
PS C:\Users\IFL\Desktop\Liu\Detector\CornerNet-Lite-master> conda activate CornerNet_Lite
PS C:\Users\IFL\Desktop\Liu\Detector\CornerNet-Lite-master>
