### ISSUE TITLE
how to solve the issue "None type has attribute shape"

### ISSUE THREAD

**Issue by jiangkunkun1993** [princeton-vl/CornerNet-Lite#97]
我是按照作者的目录放置的文件，代码也不会有错，但是运行的时候出现了“None type has attribute
shape”后来同事提醒发现，应该把minival2014里面的图片全部复制然后放到trainval2014里面合并在一块。然后就训练成功跑通了。

**Comment by sunshangyun** [comment]
make sure your image data dir is right in " CornerNet-Squeeze.json -->data_dir" and "dbs\coco.py"

**Comment by zhiyingf** [comment]
I only have one GPU,so setting the "batch_size": 12 and "chunk_sizes": [12] in the CornerNet_Saccade.json. When I run python train.py CornerNet_Saccade --workers 1 , 
the problem is:
Traceback (most recent call last):
  File "train.py", line 55, in prefetch_data
    data, ind = sample_data(system_config, db, ind, data_aug=data_aug)
  File "/home/fzysnnu/CornerNet-Lite/core/sample/__init__.py", line 5, in data_sampling_func
    return globals()[sys_configs.sampling_function](sys_configs, db, k_ind, data_aug, debug)
  File "/home/fzysnnu/CornerNet-Lite/core/sample/cornernet_saccade.py", line 171, in cornernet_saccade
    border     = [0, image.shape[0], 0, image.shape[1]]
AttributeError: 'NoneType' object has no attribute 'shape'
To find this problem,I add a code--print(image_path) in the CornerNet_Saccade.py,the result is:
,./data/coco/images/trainval2014/COCO_val2014_000000142323.jpg.

**Comment by Sherry0815** [comment]
为什么我合并了还是这个错误。。。哭了

**Comment by zhiyingf** [comment]
就是应该合并的，这个数据集的使用和faster-rcnn,你尝试将中间结果输出，比如将imagepath输出。一般出现这个错误是因为没有读到图片。



---Original---

**Comment by mdswyz** [comment]
标签和图片有误
